### ISSUE TITLE
Build is broken in Node.js 10

### ISSUE THREAD

**Issue by pepelsbey** [shower/shower#313]
```
$ nvm use 10
Now using node v10.1.0 (npm v6.0.1)
$ npm run prepare

> shower@2.3.0 prepare /Users/pepelsbey/Documents/Shower/shower
> gulp prepare

gulp[13361]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/Users/pepelsbey/.nvm/versions/node/v10.1.0/bin/node]
 2: node::InternalCallbackScope::~InternalCallbackScope() [/Users/pepelsbey/.nvm/versions/node/v10.1.0/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/pepelsbey/.nvm/versions/node/v10.1.0/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/pepelsbey/.nvm/versions/node/v10.1.0/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/pepelsbey/.nvm/versions/node/v10.1.0/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/pepelsbey/.nvm/versions/node/v10.1.0/bin/node]
 7: 0x30a6ad30427d
 8: 0x30a6ad30f755
 9: 0x30a6ad38bc20
10: 0x30a6ad3144f7
11: 0x30a6ad3144f7
12: 0x30a6ad3144f7
```

Any idea?

**Comment by pepelsbey** [comment]
Looks like [Native crash in Node 10](https://github.com/gulpjs/gulp/issues/2162#issuecomment-385197164)

**Comment by avdeev** [comment]
Reproduce

```
Mac-mini-Alexey:shower alexeyavdeev$ npm i

> fsevents@1.1.2 install /Users/alexeyavdeev/projects/shower/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.2.1 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.2.1 (node-v64 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
In file included from In file included from ../../nan/nan.h../../nan/nan.h::192192:
:
../../nan/nan_maybe_43_inl.h:112:15../../nan/nan_maybe_43_inl.h:: 112:15error::  error: no member named 'ForceSet' inno 'v8::Object'
member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from In file included from ../fsevents.cc:6:
../fsevents.cc:../../nan/nan.h6::
834:../../nan/nan.h18::834 :18:warning : warning'MakeCallback':  is 'MakeCallback'deprecated:  isUse  deprecated:MakeCallback(...,  Useasync_context)  MakeCallback(...,[-Wdeprecated-declarations] async_context)
 [-Wdeprecated-declarations]
    return node::MakeCallback(
    return node::MakeCallback(
                 ^
                 ^
/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h:171:1: /Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h:171note:: 1:'MakeCallback'  has notebeen:  explicitly'MakeCallback' has been explicitly  marked deprecated here
marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h:88:20: /Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h:88note:: 20:expanded  from notemacro:  'NODE_DEPRECATED'expanded
from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::849849::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h::164164::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom  macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::864864::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h::157157::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom  macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from In file included from ../fsevents.cc:../fsevents.cc6::
6:
../../nan/nan.h../../nan/nan.h::14731473::3131::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return scope.Escape(node::MakeCallback(    return scope.Escape(node::MakeCallback(

                              ^                              ^

/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h::171171::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h/Users/alexeyavdeev/.node-gyp/10.2.1/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom  macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gypgyp  ERR!ERR!  build errorbuild error

gypgyp  ERR!ERR! stack  Error: `make` failed with exit code: 2
stackgyp Error: `make` failed with exit code: 2
 gypERR!  ERR!stack      at ChildProcess.onExit (/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
stackgyp      at ChildProcess.onExit (/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR!ERR!  stackstack     at ChildProcess.emit (events.js:182:13)
     at ChildProcess.emit (events.js:182:13)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gypgyp  ERR!ERR!  SystemSystem Darwin 17.5.0
 Darwin 17.5.0
gypgyp  ERR!ERR!  command "/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node" "/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
commandgyp ERR!  "/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node" "/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
cwd /Users/alexeyavdeev/projects/shower/node_modules/fsevents
gypgyp  ERR!ERR!  node -vcwd v10.2.1
 /Users/alexeyavdeev/projects/shower/node_modules/fsevents
gypgyp  ERR!ERR! node -v  v10.2.1
node-gyp -v v3.6.2
gyp ERR! gypnode-gyp -v v3.6.2
 ERR!gyp  ERR!not ok
 not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node /Users/alexeyavdeev/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/alexeyavdeev/projects/shower/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node" "/Users/alexeyavdeev/projects/shower/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/alexeyavdeev/projects/shower/node_modules/fsevents
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node /Users/alexeyavdeev/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/alexeyavdeev/projects/shower/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> shower@2.3.0 prepare /Users/alexeyavdeev/projects/shower
> gulp prepare

gulp[5799]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/alexeyavdeev/.nvm/versions/node/v10.2.1/bin/node]
 7: 0x3edeab10427d
 8: 0x3edeab10f755
 9: 0x3edeab18bc20
10: 0x3edeab1144f7
11: 0x3edeab1144f7
12: 0x3edeab1144f7
Abort trap: 6
```

**Comment by avdeev** [comment]
Solution from https://github.com/gulpjs/gulp/issues/2162#issuecomment-384885950 is working.

I updated package-lock at https://github.com/shower/shower/commit/3f2bde797102203282de4e41e5db1744f24e8446

@pepelsbey Try to reproduce, plz

**Comment by pepelsbey** [comment]
Closing as fixed, I guess.
